#!/bin/bash

. functions
cd $LFS/sources

# binutils
extract_archive binutils-2.25.1.tar.bz2

if [ -d binutils-build ]; then
    rm -rf binutils-build
elif [ -f binutils-build ]; then
    echo 'binutils-build is a file'
    exit 1
fi
mkdir -pv binutils-build
cd binutils-build

# configure
../binutils-2.25.1/configure   \
    --prefix=/tools        \
    --with-sysroot=$LFS        \
    --with-lib-path=/tools/lib \
    --target=$LFS_TGT          \
    --disable-nls              \
    --disable-werror

# make
make

# install
case $(uname -m) in
  x86_64) mkdir -v /tools/lib && ln -sv lib /tools/lib64 ;;
esac
make install

# cleanup
#rm -rf binutils-build
#rm -rf ../binutils-2.25.1
