#!/bin/bash

. functions
cd $LFS/sources

extract_archive gcc-5.2.0.tar.bz2
cd gcc-5.2.0

mkdir -vp ../gcc-build
cd ../gcc-build

../gcc-5.2.0/libstdc++-v3/configure \
    --host=$LFS_TGT                 \
    --prefix=/tools                 \
    --disable-multilib              \
    --disable-nls                   \
    --disable-libstdcxx-threads     \
    --disable-libstdcxx-pch         \
    --with-gxx-include-dir=/tools/$LFS_TGT/include/c++/5.2.0

make
make install
