#!/bin/bash

. functions
cd $LFS/sources

extract_archive glibc-2.22.tar.xz

cd glibc-2.22

patch -Np1 -i ../glibc-2.22-upstream_i386_fix-1.patch

mkdir -vp ../glibc-build
cd ../glibc-build

../glibc-2.22/configure                             \
      --prefix=/tools                               \
      --host=$LFS_TGT                               \
      --build=$(../glibc-2.22/scripts/config.guess) \
      --disable-profile                             \
      --enable-kernel=2.6.32                        \
      --enable-obsolete-rpc                         \
      --with-headers=/tools/include                 \
      libc_cv_forced_unwind=yes                     \
      libc_cv_ctors_header=yes                      \
      libc_cv_c_cleanup=yes

make
make install

echo 'int main(){}' > dummy.c
$LFS_TGT-gcc dummy.c
if [ -z $(readelf -l a.out | grep ': /tools') ]; then
    echo "GLib dummy compilation test failed"
    exit 1
fi
rm -v dummy.c a.out

cd $LFS/sources
cd glibc-2.22
cd glibc-build
